providers = ["node", "python"]

[variables]
NODE_ENV = "production"
SECRET_KEY = "django-insecure-ud@*yx(aj5%4#wxhb7@p*lwqz4x_5_9abf8zhku$x&4nyc01ld"

[phases.build]
cmds = ["cd client", "npm install", "npm run build", "cd .."]